In [1]:
import torch
import numpy as np

In [2]:
a = torch.ones(2, 3)
print(a)


 1  1  1
 1  1  1
[torch.FloatTensor of size 2x3]



In [3]:
a = torch.zeros(2, 3)
print(a)


 0  0  0
 0  0  0
[torch.FloatTensor of size 2x3]



In [4]:
# identity matrix
a = torch.eye(3)
print(a)
a = torch.eye(2, 3)
print(a)


 1  0  0
 0  1  0
 0  0  1
[torch.FloatTensor of size 3x3]


 1  0  0
 0  1  0
[torch.FloatTensor of size 2x3]



In [5]:
# size & number of elements
a = torch.ones(2, 3, 4)
print(a.size())
print(a.numel())

torch.Size([2, 3, 4])
24


In [6]:
x = np.ones([3, 4])
print(x)
a = torch.from_numpy(x)
print(a)
b = torch.eye(3, 4)
print(b)
c = a.float() + b
print(c)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]

 1  1  1  1
 1  1  1  1
 1  1  1  1
[torch.DoubleTensor of size 3x4]


 1  0  0  0
 0  1  0  0
 0  0  1  0
[torch.FloatTensor of size 3x4]


 2  1  1  1
 1  2  1  1
 1  1  2  1
[torch.FloatTensor of size 3x4]



In [7]:
a = torch.linspace(-5, 5, steps=10)
print(a)


-5.0000
-3.8889
-2.7778
-1.6667
-0.5556
 0.5556
 1.6667
 2.7778
 3.8889
 5.0000
[torch.FloatTensor of size 10]



In [8]:
a = torch.eye(2, 2)
print(a)
b = torch.clamp(a, 0.25, 0.75)
print(b)
c = a.clamp(0.25, 0.75)
print(c)
a.clamp_(0.25, 0.75)
print(a)


 1  0
 0  1
[torch.FloatTensor of size 2x2]


 0.7500  0.2500
 0.2500  0.7500
[torch.FloatTensor of size 2x2]


 0.7500  0.2500
 0.2500  0.7500
[torch.FloatTensor of size 2x2]


 0.7500  0.2500
 0.2500  0.7500
[torch.FloatTensor of size 2x2]

